### ISSUE TITLE
route:list will not work

### ISSUE THREAD

**Issue by obayesshelton** [shnhrrsn/laravel-assets#1]
Hi,

When I run `route:list` within Laravel5 I get the following error:

`[2015-03-23 15:30:36] production.ERROR: exception 'ErrorException' with message 'Undefined index: REQUEST_URI' in /www/katana/vendor/shnhrrsn/laravel-assets/Http/Controller.php:14
Stack trace:
#0 /www/katana/vendor/shnhrrsn/laravel-assets/Http/Controller.php(14): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/www/katana/ven...', 14, Array)
#1 [internal function]: Assets\Http\Controller->__construct()
#2 /www/katana/vendor/laravel/framework/src/Illuminate/Container/Container.php(817): ReflectionClass->newInstanceArgs(Array)
#3 /www/katana/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('\Assets\Http\Co...', Array)
#4 /www/katana/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Container\Container->make('\Assets\Http\Co...', Array)
#5 /www/katana/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(161): Illuminate\Foundation\Application->make('\Assets\Http\Co...')
#6 /www/katana/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(142): Illuminate\Foundation\Console\RouteListCommand->getControllerMiddleware('\Assets\Http\Co...')
#7 /www/katana/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(109): Illuminate\Foundation\Console\RouteListCommand->getMiddleware(Object(Illuminate\Routing\Route))
#8 /www/katana/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(89): Illuminate\Foundation\Console\RouteListCommand->getRouteInformation(Object(Illuminate\Routing\Route))
#9 /www/katana/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php(75): Illuminate\Foundation\Console\RouteListCommand->getRoutes()
#10 [internal function]: Illuminate\Foundation\Console\RouteListCommand->fire()
#11 /www/katana/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#12 /www/katana/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#13 /www/katana/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/katana/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /www/katana/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /www/katana/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /www/katana/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /www/katana/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /www/katana/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}  `

**Comment by shnhrrsn** [comment]
Sorry about that, this should be resolved now in v1.0.2

**Comment by obayesshelton** [comment]
Thanks :+1:
